openapi: 3.0.0
info:
  title: epok-mock
  version: '1.0'
  contact:
    email: weleoka@gitlab.com
    name: Kai Weeks
  license:
    name: MIT
  description: API service for EPOK which handles courses and instances as well as the defined modules.
servers:
  - url: 'http://localhost:8282'
    description: host-network
  - url: 'http://nodemocks'
    description: docker-network
paths:
  /modules:
    get:
      summary: Your GET endpoint
      tags:
        - epok
        - mock
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/module'
      operationId: get-modules
      description: Modules can be found by different search parameters. Common would be to search for them by Code and status.
      parameters:
        - schema:
            type: string
          in: query
          name: module_id
        - schema:
            type: string
          in: query
          name: description
        - schema:
            type: string
          in: query
          name: status
        - schema:
            type: string
          in: query
          name: course_code
    parameters: []
components:
  schemas:
    module:
      title: Modul
      type: object
      x-tags:
        - epok
        - mock
      description: A module belongs to a course. It can be acktive or iactive.
      properties:
        module_id:
          type: string
        description:
          type: string
          description: Translates to benämning.
        status:
          type: string
          description: active or non-active
        course_code:
          type: string
tags:
  - name: epok
  - name: mock
